# BigBlueButton Solution
#
# template for big-blue-button-on-aws-cn
# **DO NOT DELETE**
#
# author: aws-gcr-solution-center@
AWSTemplateFormatVersion: 2010-09-09

Description: (BigBlueButton) - Solution - Master Template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General AWS
      Parameters:
        - EC2KeyName
        - SshAccessCidr
    - Label:
        default: Network
      Parameters:
        - VpcId
        - Subnet
    - Label:
        default: BigBlueButton General Information
      Parameters:
        - Email
        - SecretId
    - Label:
        default: Turn Server
      Parameters:
        - TurnServerInstanceType
        - TurnServerDomainName
        - TurnServerEIPAllocationID
        - TurnServerDiskSize
    - Label:
        default: App Server
      Parameters:
        - AppServerInstanceType
        - AppServerDomainName
        - AppServerEIPAllocationID
        - AppServerDiskSize
    - Label:
        default: Greenlight Admin Account
      Parameters:
        - GreenlightAccountName
        - GreenlightAccountEmail
        - GreenlightAccountPassword
    ParameterLabels:
      EC2KeyName:
        default: EC2 Key Pair
      VpcId:
        default: VPC ID
      Subnet:
        default: Subnet ID
      SshAccessCidr:
        default: SSH Access From
      Email:
        default: Email
      SecretId:
        default: Secret ID
      TurnServerInstanceType:
        default: Instance Type
      TurnServerDomainName:
        default: Domain Name
      TurnServerDiskSize:
        default: Disk Size
      TurnServerEIPAllocationID:
        default: EIP Allocation ID
      AppServerInstanceType:
        default: Instance Type
      AppServerDomainName:
        default: Domain Name
      AppServerDiskSize:
        default: Disk Size
      AppServerEIPAllocationID:
        default: EIP Allocation ID
      GreenlightAccountName:
        default: Account Name
      GreenlightAccountEmail:
        default: Email
      GreenlightAccountPassword:
        default: Password

Parameters:
  EC2KeyName:
    Description: Exisitng EC2 Key Name
    Type: AWS::EC2::KeyPair::KeyName
  SshAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    Default: 0.0.0.0/0
    Description: The CIDR IP range that is permitted to SSH to bastion instance. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
  VpcId:
    Description: ID of existing VPC
    Type: AWS::EC2::VPC::Id
  Subnet:
    Description: ID of public subnet, you MUST choose an public subnet.
    Type: AWS::EC2::Subnet::Id
  Email:
    Description: The Email address for Let's encrypt to generate SSL Certificate
    Type: String
    AllowedPattern: \w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}
  SecretId:
    Description: The Secret for inter-communication between Turn and App Server
    Type: String
    Default: "12345678"
  TurnServerInstanceType:
    Description: Choose an instance type of Turn server
    AllowedValues:
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: c5.large
    Type: String
  TurnServerDomainName:
    Description: The domain of of the turn server. This is required for production environment
    Type: String
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
  TurnServerDiskSize:
    Description: The Disk size of Turn Server
    Type: Number
    Default: 100
  TurnServerEIPAllocationID:
    Description: The EIP Allocation ID of turn server, you MUST configure DNS record first. e.g. eipalloc-079f15392865107a2
    Type: String
    AllowedPattern: ^eipalloc-[0-9a-z]*
  AppServerInstanceType:
    Description: Choose an instance type of App server, you need at least 4 cores in production environement.
    AllowedValues:
      - t3.xlarge
      - t3.2xlarge
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: c5.2xlarge
    Type: String
  AppServerDomainName:
    Description: The domain of of the App server. This is required for production environment
    Type: String
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
  AppServerDiskSize:
    Description: The Disk size of App Server
    Type: Number
    Default: 100
  AppServerEIPAllocationID:
    Description: The EIP Allocation ID of App server, you MUST configure DNS record first. e.g. eipalloc-079f15392865107a2
    Type: String
    AllowedPattern: ^eipalloc-[0-9a-z]*
  GreenlightAccountName:
    Description: Input the Admin user name
    Type: String
    Default: Admin
  GreenlightAccountEmail:
    Description: Account email for the admin user
    Type: String
    AllowedPattern: \w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}
  GreenlightAccountPassword:
    Description: Password for the admin user
    Type: String
    NoEcho: true

Resources:

  securitygroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SshAccessCidr:
          !Ref SshAccessCidr
        VpcId:
          !Ref VpcId
      TemplateURL: https://s3.cn-north-1.amazonaws.com.cn/%%TEMPLATE_BUCKET_NAME%%/%%SOLUTION_NAME%%/%%VERSION%%/01-security-groups.template

  iamroles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.cn-north-1.amazonaws.com.cn/%%TEMPLATE_BUCKET_NAME%%/%%SOLUTION_NAME%%/%%VERSION%%/01-iam-roles.template

  turnserver:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        InstanceType:
          !Ref TurnServerInstanceType
        DomainName:
          !Ref TurnServerDomainName
        DiskSize:
          !Ref TurnServerDiskSize
        SecretId:
          !Ref SecretId
        Email:
          !Ref Email
        EC2KeyName:
          !Ref EC2KeyName
        SecurityGroup:
          !GetAtt [securitygroups, Outputs.TurnSecurityGroup]
        Subnet:
          !Ref Subnet
        EIPAllocationId:
          !Ref TurnServerEIPAllocationID
        InstanceProfile:
          !GetAtt [iamroles, Outputs.InstanceProfile]
      TemplateURL: https://s3.cn-north-1.amazonaws.com.cn/%%TEMPLATE_BUCKET_NAME%%/%%SOLUTION_NAME%%/%%VERSION%%/02-turn-server.template

  appserver:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        InstanceType:
          !Ref AppServerInstanceType
        DomainName:
          !Ref AppServerDomainName
        DiskSize:
          !Ref AppServerDiskSize
        SecretId:
          !Ref SecretId
        Email:
          !Ref Email
        EC2KeyName:
          !Ref EC2KeyName
        SecurityGroup:
          !GetAtt [securitygroups, Outputs.AppSecurityGroup]
        Subnet:
          !Ref Subnet
        TurnServerEndpoint:
          !GetAtt [turnserver, Outputs.TurnServerEndpoint]
        EIPAllocationId:
          !Ref AppServerEIPAllocationID
        InstanceProfile:
          !GetAtt [iamroles, Outputs.InstanceProfile]
        GreenlightAccountName:
          !Ref GreenlightAccountName
        GreenlightAccountEmail:
          !Ref GreenlightAccountEmail
        GreenlightAccountPassword:
          !Ref GreenlightAccountPassword
      TemplateURL: https://s3.cn-north-1.amazonaws.com.cn/%%TEMPLATE_BUCKET_NAME%%/%%SOLUTION_NAME%%/%%VERSION%%/02-app-server.template

Outputs:
  TurnServerEndpoint:
    Description: Turn Server Endpoint
    Value: !GetAtt [turnserver, Outputs.TurnServerEndpoint]
  AppServerEndpoint:
    Description: App Server Endpoint
    Value: !GetAtt [appserver, Outputs.AppServerEndpoint]
  GreenlightAdminEmail:
    Description: Email for the admin user. Use for to login into BigBlueButton.
    Value: !Ref GreenlightAccountEmail
